apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: retailsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          args: ["server", "--host", "0.0.0.0", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlruns"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlruns
              mountPath: /mlruns
      volumes:
        - name: mlruns
          emptyDir: {}
